DEEPSEEK_API_KEY = "sk-61f896fa87684ed3bddb880ef1dd0bcb"
SUPABASE_URL = "https://xiwjagypvxexejudlfip.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhpd2phZ3lwdnhleGVqdWRsZmlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5MTg3MTgsImV4cCI6MjA3ODQ5NDcxOH0.jWr6y6GxZWS0KqXrK5KXK_hPnvVeLOnBZ1TZxazJrGg"
APP_PASSWORD = "1234"